version: '3.8'
services:

  gitlab-server:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-server
    environment:
      GITLAB_ROOT_EMAIL: "admin@buildwithlal.com"
      GITLAB_ROOT_PASSWORD: "Abcd@0123456789"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8000'
        nginx['listen_port'] = 8000
      GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: r3g1str4t10n
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    ports:
      - '8000:8000'
    healthcheck:
      test: curl --fail http://localhost:8000/users/sign_in || exit 1
      interval: 60s
      timeout: 3s
      retries: 5

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    entrypoint: [""]
    command: ["/bin/sh", "-c", "gitlab-runner register \
                                      --non-interactive \
                                      --url 'http://localhost:8000' \
                                      --registration-token 'r3g1str4t10n' \ 
                                      --executor 'docker' \
                                      --docker-network-mode 'host' \
                                      --docker-image 'python:alpine' \
            && gitlab-runner run --user=gitlab-runner --working-directory=/etc/gitlab-runner"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   
    network_mode: 'host'
    depends_on:
      gitlab-server: 
        condition: service_healthy
