build with shell executor:
  stage: build
  tags:
    - shell
  script:
    - date # print current date
    - cat /etc/os-release # print os version for Linux

build with docker executor:
  stage: build
  tags:
    - docker
  image: docker:24.0.5

  # new changes for adding dummy containers
  script:
    - docker run -d --rm --name nested-container1-in-pipelinejob alpine sleep 20
    - docker run -d --rm --name nested-container2-in-pipelinejob alpine sleep 20

build with docker executor default image: # default python image
  stage: build
  tags:
    - docker
  script:
    - python --version
    - sleep 10

build with docker in docker:
  stage: build
  image: docker:27.2.0
  services:
    - docker:27.2.0-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"

  tags:
    - docker-in-docker
  script:
    - docker ps
    - docker run -d --rm --name nested-container1-in-pipelinejob alpine sleep 20
    - docker run -d --rm --name nested-container2-in-pipelinejob alpine sleep 20
    - docker ps
    - sleep 20
