build with docker in docker:
  stage: build
  image: docker:27.2.0
  services:
    - docker:27.2.0-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"

  tags:
    - docker-in-docker
  script:
    - docker ps
    - docker run -d --rm --name nested-container1-in-pipelinejob alpine sleep 20
    - docker run -d --rm --name nested-container2-in-pipelinejob alpine sleep 20
    - docker ps
    - sleep 20
