concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "kaniko"
  url = "http://localhost:8000"
  id = 3
  token = "glrt-nixxps7WADnsVbJDZxES"
  token_obtained_at = 2024-09-22T15:40:15Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:27.2.0"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    network_mode = "host"
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "kubernetes"
  url = "http://localhost:8000"
  id = 4
  token = "glrt-ZPjS7L_cLcDzZyu7UyGz"
  token_obtained_at = 2024-09-22T15:56:50Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "kubernetes"
  clone_url = "http://gitlab-server:8000"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.kubernetes]
    host = "https://localhost:46811"
    cert_file = "/etc/gitlab-runner/kubernetes/cert/apiserver-kubelet-client.crt"
    key_file = "/etc/gitlab-runner/kubernetes/cert/apiserver-kubelet-client.key"
    ca_file = "/etc/gitlab-runner/kubernetes/cert/ca.crt"
    bearer_token_overwrite_allowed = false
    privileged = true
    image = ""
    namespace = ""
    namespace_overwrite_allowed = ""
    namespace_per_job = false
    node_selector_overwrite_allowed = ""
    node_tolerations_overwrite_allowed = ""
    pod_labels_overwrite_allowed = ""
    service_account_overwrite_allowed = ""
    pod_annotations_overwrite_allowed = ""
    [runners.kubernetes.init_permissions_container_security_context]
      [runners.kubernetes.init_permissions_container_security_context.capabilities]
    [runners.kubernetes.build_container_security_context]
      [runners.kubernetes.build_container_security_context.capabilities]
    [runners.kubernetes.helper_container_security_context]
      [runners.kubernetes.helper_container_security_context.capabilities]
    [runners.kubernetes.service_container_security_context]
      [runners.kubernetes.service_container_security_context.capabilities]
    [runners.kubernetes.volumes]
    [runners.kubernetes.dns_config]
    [[runners.kubernetes.volumes.secret]]
           name = "runner-cert"
           mount_path = "/etc/gitlab-runner/certs/"
