build:
    stage: build
    tags:
        - kubernetes
    image:
        # name: gcr.io/kaniko-project/executor:v1.23.2-debug
        # entrypoint: [""]
        name: docker:27.2.0
      
    # before_script:
        # - echo "{\"insecure-registries\":[\"dockerhost:5001\"]}" > /etc/docker/daemon.json
    #     - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    
    script:
        # - cat /kaniko/.docker/config.json
        # - cat /etc/docker/daemon.jsn
        - cp /etc/gitlab-runner/certs/ca.crt /usr/local/share/ca-certificates/
        - update-ca-certificates
        - echo $CI_REGISTRY_IMAGE
        - echo $CI_REGISTRY
        - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
        - docker build -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}" .
        - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}"
        - /kaniko/executor --skip-tls-verify --verbosity debug --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}"

# build:
#     stage: build
#     tags:
#         - kaniko
#     image:
#         name: gcr.io/kaniko-project/executor:v1.23.2-debug
#         entrypoint: [""]
      
#     # before_script:
#     #     - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    
#     script:
#         # - cat /kaniko/.docker/config.json
#         - /kaniko/executor --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}"
