build:
    stage: build
    image: docker:latest
    tags:
        - docker
    script:
        - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}" .
        - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}"
