build with kaniko:
  stage: build
  tags:
    - kaniko
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  before_script:
    # registry URL: https://index.docker.io/v1/
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "REGISTRY_USERNAME" "REGISTRY_PASSWORD" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:

    - echo ${CI_PROJECT_DIR}

    # conventional project with Dockerfile inside root dir
    - /kaniko/executor --no-push

    # Dockerfile is in some other directory than root dir
    - /kaniko/executor --no-push --dockerfile "${CI_PROJECT_DIR}/src/mydockerfile"

    - /kaniko/executor
      --dockerfile "${CI_PROJECT_DIR}/src/Dockerfile"
      --destination "REGISTRY_USERNAME/REGISTRY_REPO_NAME:${CI_COMMIT_TAG}"



