version: '3.8'
services:

  gitlab-server:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-server
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8088'
        nginx['listen_port'] = 8088
        gitlab_rails['initial_root_password'] = 'Abcd@0123456789'
        puma['worker_processes'] = 0 # disable cluster mode to avoid more memory usage
      GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: r3g1str4t10n
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    ports:
      - '8088:8088'
    healthcheck:
      test: curl --fail http://localhost:8088/users/sign_in || exit 1
      interval: 60s
      timeout: 3s
      retries: 5

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    entrypoint: [""]
    command: ["/bin/sh", "-c", "gitlab-runner register \
                                      --non-interactive \
                                      --url 'http://localhost:8088' \
                                      --registration-token 'r3g1str4t10n' \ 
                                      --executor 'docker' \
                                      --docker-network-mode 'host' \
                                      --docker-image 'python:alpine' \
            && gitlab-runner run --user=gitlab-runner --working-directory=/etc/gitlab-runner"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   
    network_mode: 'host'
    depends_on:
      gitlab-server: 
        condition: service_healthy
